### ISSUE TITLE
Ignore .spec.js and .stories.js files

### ISSUE THREAD

**Issue by shahidshaikhs** [wobsoriano/vue-sfc-unbuild#3]
When I try to build the library using `npm run build` command, all the files inside the components folder are moved to the build.

My component folder also incudes .spec.js and .stories.js files as well.

How can we ignore these files while building?

**Comment by wobsoriano** [comment]
You can add a pattern option to the build config:

```ts
const pattern = ['**/*', '!**/*test*.*']

export default defineBuildConfig({
  entries: [
    { builder: 'mkdist', input: './src/', pattern },
    { builder: 'mkdist', input: './src/', format: 'cjs', ext: 'cjs', pattern },
  ],
  declaration: true,
})
```

`'**/*'`: Matches all files and directories recursively.
`'!**/*test*.*'`: Excludes any file or directory containing "test" in its name.
